### ISSUE TITLE
Game saves are broken

### ISSUE THREAD

**Issue by Kippykip** [doomhack/GBADoom#1]
Just letting you know that loading/saving is broken, and always loads E1M9, for Ultimate doom it loads E4M9, and on Doom 2+ it crashes with a unknown music lump of some random negative number.

This is an amazing port honestly, I hope to see it become a complete replacement to the official ones. (Which has already mostly done that for me!)

**Comment by doomhack** [comment]
Can you reliably reproduce this? If you remove the save file from the flash card and then do a save-load?

I don’t think I’ve made any breaking changes to the save format (not in released versions anyway)


The only other thing that comes to mind is a wait-state issue. Saves are done using a memory copy to the SRAM region. Maybe some flash cards need different wait states?

**Comment by doomhack** [comment]
There is an issue where loading an unused save slot would read garbage from the SRAM area. I've added a partial fix for this.

**Comment by Kippykip** [comment]
Awesome! I'll have to test saving on an EZ Flash IV as this whole time I've been testing this in the VBA emulator.

**Comment by Kippykip** [comment]
Can confirm saves are working and check if it's an empty slot.
And for future references guys, to get it saving on VBA, goto 
**Options>Emulator>Save Type>SRAM**
That should fix it!

**Comment by Squall-Leonhart** [comment]
> **Options>Emulator>Save Type>SRAM**

This should be fixed in THIS project, the SRAM_Vnnn string is a part of all legitimate roms, and this one is missing it.
