### ISSUE TITLE
can't play game when using the start button

### ISSUE THREAD

**Issue by heckez-sys** [doomhack/GBADoom#11]

**Comment by Kippykip** [comment]
Um, can you be more elaborate?

**Comment by heckez-sys** [comment]
i have to press the b button unlike the dos doom where you press enter(aka start)

**Comment by Kippykip** [comment]
So... is your menus getting stuck or something?
For menus and such, Start is basically the ESC key like as if it was the Dos version, A is enter, B is back (which is a new feature in this port that wasn't in the DOS version).

Or do you mean something else entirely?
