### ISSUE TITLE
Sky Rendering Glitch

### ISSUE THREAD

**Issue by BloxyGuardian** [doomhack/GBADoom#14]
It's more of a glitch with the map but in certain maps, You can see beyond the sky, I linked an image of it.
![image](https://user-images.githubusercontent.com/68078283/88975910-f7ded480-d26f-11ea-8176-701deebcb29d.png)

**Comment by doomhack** [comment]
I believe this happens because the aspect ratio is slightly different. 120x128 pixel doubled in the X direction.

**Comment by BloxyGuardian** [comment]
> I believe this happens because the aspect ratio is slightly different. 120x128 pixel doubled in the X direction.
This exact effect also happens in GZDoom, Even with classic 4:3 and 320x200. So it's definitely because of the map although the resolution may have something to do with it, It's also handled differently, The sky is just repeated in GZDoom. If we can't find a solution than here's my solution: Skies are stretched so in any map where this hasn't been discovered yet (Especially E1M1) This is impossible to see.

**Comment by doomhack** [comment]
Adding assets is not the easiest way to fix this.

There is already a scaling factor for the sky texture.

Changing:

`static const fixed_t skyiscale = (FRACUNIT*200)/(SCREENHEIGHT-ST_HEIGHT);`

to:

`static const fixed_t skyiscale = (FRACUNIT*200)/((SCREENHEIGHT-ST_HEIGHT)+16);`

Means that the texture will stretch down another 16px and so the wrap is no longer visible.

I think this is also an issue in vanilla Doom. I'm pretty sure I remember seeing this when I was kid!
