### ISSUE TITLE
Game will occasionally pause controls

### ISSUE THREAD

**Issue by BloxyGuardian** [doomhack/GBADoom#15]
It's hard to describe this issue and I haven't tested it out on my GBA for I don't have a EZFlash. But this is certainly an engine issue although I'm not 100% sure that it happens on real hardware, It definitely can happen on emulator, For proof that this is an engine issue, I've had this exact issue on PC Source ports, More specifically Odamex, As far as I can tell, It happens if you do something incorrectly or change something you aren't supposed to. So here's the issue
Out of absolutely NOWHERE, The game might have a lag spike, I know that's normal, But this is a bad lag spike, Like the emulator itself will freeze. Once that lag spike is over, You'll be completely frozen, The demons will still move but you will lose all control, You can't pause the game and the only fix is to restart the console/emulator. This doesn't happen on any other game. The situation plays out the exact same on Odamex if your wondering. At a glance it'd be a console issue but in reality it's 100% a problem with this homebrew. Alongside that, This issue hasn't ever happened to me on GBA Doom 1 on real hardware or an emulator and GBA Doom 1 is internally identical to PRBoom GBA.

**Comment by jimeral** [comment]
bruhm shut the fuck up

**Comment by Kippykip** [comment]
Sounds more like you have an issue with your computer Bloxy.
Otherwise if you can give us steps to replicate the problem, I can test it out. Plus I'd like to know which GBA emulator you are using.

In my case I've completed PrBoom Doom 1 on real hardware and on the VBA-M emulator without any control locking issues or random freezes at all. Also retail GBA Doom 1 and PrBoom are still very very different as that's based on the Jaguar port while this is based on the PrBoom community ports.

Also Bloxy, if this is yet another one of your _GBA Doom reddit stunts_ to get a reaction, we'd prefer you to leave it out of this github's issues panel.

**Comment by BloxyGuardian** [comment]
> Sounds more like you have an issue with your computer Bloxy.
> Otherwise if you can give us steps to replicate the problem, I can test it out. Plus I'd like to know which GBA emulator you are using.
> 
> In my case I've completed PrBoom Doom 1 on real hardware and on the VBA-M emulator without any control locking issues or random freezes at all. Also retail GBA Doom 1 and PrBoom are still very very different as that's based on the Jaguar port while this is based on the PrBoom community ports.
> 
> Also Bloxy, if this is yet another one of your _GBA Doom reddit stunts_ to get a reaction, we'd prefer you to leave it out of this github's issues panel.

1. It isn't a stunt, PRBoom GBA cancelled out the Final Doom GBA port
2. Stop acting like this is a business man you don't have to be professional to your friends just because it's public
3. Alright so there's no way to tell if it's my computer and there's no way to replicate the issue, It just happens at random
4. My emulator is Visual Boy Advance

**Comment by doomhack** [comment]
If the emulator is wedging, then its going to be your computer that is acting up.

The emulator doesn't care if the game is wedged. It's just instructions at the end of the day. I don't think VBA does any trick dynarec stuff so the game borking out won't crash the emulator.
