### ISSUE TITLE
Save type

### ISSUE THREAD

**Issue by badass-boss** [doomhack/GBADoom#17]
What sort of save type does the PC DOOM 1 port use?? The emulator reports it as size 64KBytes but I can't dig out any more info. Please reply, many thanks in advance

**Comment by doomhack** [comment]
Hi,

The game saves data to SRAM.

**Comment by Squall-Leonhart** [comment]
Your builds and the the forked romhack do not include SRAM_Vnnn/SRAM_F_Vnnn, which most emulators use to ascertain the save type automatically.

You can place this anywhere within the rom so long as its within worked aligned and a multiple of 4 bytes.
