### ISSUE TITLE
Icon of Sin is blind

### ISSUE THREAD

**Issue by Kippykip** [doomhack/GBADoom#2]
Just noticed the icon of sin only starts doing his _thing_ once you shoot, here's a save file which has MAP30 enabled.
[GBADoom-Hud.zip](https://github.com/doomhack/GBADoom/files/4026651/GBADoom-Hud.zip)

Good luck with the project! I'm having so much fun messing with this! 😀

**Comment by doomhack** [comment]
Fixed.

Boss brain can now see infinite distance. Maybe should also make spider demon and cyberdemon the same?
