### ISSUE TITLE
Question about tracker music

### ISSUE THREAD

**Issue by RetroGamer02** [doomhack/GBADoom#22]
Hey again I'm wondering if you would know how to convert 16bit midi or tracker files into 8bit or if there is an issue playing 16bit tracker files in the current engine. It seems to crash on my FreeDoom fork when trying to add its music.

Edit: Figured out the crash seems like FreeDoom music wants to use 32 audio channels but the max that seems to work is 12 so some parts of the music will have to be dropped. Still wondering if you know how to convert them into 8bit might save some file space.

**Comment by Kippykip** [comment]
I just use OpenMPT and export that to .IT files, it seems to just work with anything I've thrown at it thus far.
You may have to adjust tempos and speed however.

Also I would try to modify music to only play 6 channels or less at one time, anything higher disrupts sound effects

**Comment by RetroGamer02** [comment]
I will keep that in mind thank you. =)
