### ISSUE TITLE
Weapon sprites on the right hand side are glitchy

### ISSUE THREAD

**Issue by Kippykip** [doomhack/GBADoom#28]
After 2.2-2.3, if you equip something like the fists you'll notice some vertical rows of pixels flicker
![image](https://user-images.githubusercontent.com/33023808/146666131-cb5647eb-e79f-4969-b52a-7a45c894329f.png)
![image](https://user-images.githubusercontent.com/33023808/146666145-d543fa7c-c789-46e6-9deb-636e59b8b290.png)
![image](https://user-images.githubusercontent.com/33023808/146666170-d167cc45-2ade-401a-9363-3faadb27e1c0.png)

**Comment by GB-CG** [comment]
Can confirm on hardware too.

**Comment by doomhack** [comment]
So this is happening because I can't add numbers properly.

I put the neg one array and the screen height array in an unused pocket of VRAM but there wasn't enough space so it was overflowing into the framebuffer data.

Fixed.
