### ISSUE TITLE
gba.h and etc

### ISSUE THREAD

**Issue by EmeraldTuxedo56** [doomhack/GBADoom#35]
Whenever i "make" the file there is an error stating i dont have gba.h and gba_input.h or gba_timers.h or maxmod.h either

**Comment by RetroGamer02** [comment]
Are you using DevKitPro? https://github.com/devkitPro/installer/releases

**Comment by doomhack** [comment]
These headers are part of libgba.

https://github.com/devkitPro/libgba

If you haven't already, install the GBA Development SDK using DevKitPro.
