### ISSUE TITLE
How would I build this on Linux?

### ISSUE THREAD

**Issue by Espio419** [doomhack/GBADoom#36]

**Comment by RetroGamer02** [comment]
You need devkitpro I would start here.
If not using archlinux you first need the pacman package manager. https://devkitpro.org/wiki/devkitPro_pacman#Installing_devkitPro_Pacman
https://devkitpro.org/wiki/Getting_Started#Unix-like_platforms

**Comment by Espio419** [comment]
I got all that set up and made the doom.wad.c dile and put it in the source/iwad folder. I just don't know how to use the msys2.bat to build the game, since that seems to be a Windows thing.

**Comment by RetroGamer02** [comment]
Just type make =)

**Comment by Espio419** [comment]
That worked after rebooting. Thanks, my dude.

**Comment by Espio419** [comment]
Looks like I hit a roadblock. Loading the rom on my GBA and mGBA emulator just gives me an error "w_GetNumForName: TEXTURE1 not found". Happens with Doom 1 and 2.

**Comment by RetroGamer02** [comment]
Sounds like it can't identify what rom its trying to load. Oh did you change "doom_iwad.c"?
You need to do that to select the version you want to use.

**Comment by Espio419** [comment]
I did change it to the name of the file I made with gbawadutil

**Comment by Espio419** [comment]
Shareware version works fine.

**Comment by Espio419** [comment]
I don't know why, but it works now. I got Ultimate Doom and Doom II runnning.
