### ISSUE TITLE
Does the wipe effect work in the Windows version?

### ISSUE THREAD

**Issue by FrenkelS** [doomhack/GBADoom#43]
I'm working on a [DOS port](https://github.com/FrenkelS/GBADoom) of GBADoom and I noticed the [wipe effect didn't work in my port](https://twitter.com/FOmmetje/status/1687072729625669632). I haven't tried building the Windows version, but when I look at the code I wonder if the screen melt does work in that version.

In `f_wipe.c` `wipe_doMelt()` calls `I_GetFrontBuffer()` to get a pointer to the screen. In `i_system_e32.cpp` it returns `frontbuffer`, but this array is never drawn to the screen, right?

In my port, in `wipe_StartScreen()` I copy the back buffer to the front buffer and in `wipe_doMelt()`, in the while-loop, I explicitly draw the content of the front buffer to the screen.

**Comment by doomhack** [comment]
Hi,

No, the wipe doesn't work in Windows. The Windows version is just for testing and debugging so a few bits and peices are not implimented on Windows. On the GBA, frontbuffer is the video memory for the screen currently being displayed.
