### ISSUE TITLE
wont compile with latest devkit arm build

### ISSUE THREAD

**Issue by Cavencruiser** [doomhack/GBADoom#53]
C:/gbadoom/source/hu_lib.c: In function 'HUlib_initTextLine':
C:/gbadoom/source/hu_lib.c:80:10: error: assignment to 'const patch_t **' from incompatible pointer type 'const patch_t *' [-Wincompatible-pointer-types]
   80 |     t->f = f;
      |          ^
make[1]: *** [/opt/devkitpro/devkitARM/base_rules:39: hu_lib.o] Error 1
make: *** [Makefile:132: build] Error 2
![Screenshot (153)](https://github.com/doomhack/GBADoom/assets/93107023/d18f3cbc-ffd1-47ed-b86b-146826d2cee7)

**Comment by doomhack** [comment]
This should be fixed now.

https://github.com/doomhack/GBADoom/issues/54
