### ISSUE TITLE
source of compiler issues

### ISSUE THREAD

**Issue by Cavencruiser** [doomhack/GBADoom#54]
https://github.com/doomhack/GBADoom/blame/3bd2cf34fb66dd60f9b66efe25cc1d6945a21f74/source/hu_lib.c#L80

**Comment by Emendo12** [comment]
I have this compiler issue as well.

**Comment by FrenkelS** [comment]
What happens when you remove that line?

**Comment by doomhack** [comment]
Seems that the Doom code play fast and loose with pointer types. Assigning pointers (*) to double pointer (**) vars etc.

The code is wrong but worked before because a pointer is a pointer.....

I'll try to fix this over the next couple of evenings...

**Comment by doomhack** [comment]
Here we have it.

https://gcc.gnu.org/gcc-14/porting_to.html#warnings-as-errors

**Comment by doomhack** [comment]
Adding the -fpermissive flag 'fixes' this. The code is wrong but it's been wrong since 1993...

If you do a fresh pull, it should build with latest DevKitPro.
