### ISSUE TITLE
Saving doesn’t work with the Delta emulator

### ISSUE THREAD

**Issue by ProvokedGamer** [doomhack/GBADoom#55]
I was using this rom remake and tried to save in-game. It says that it saved but when I try to load the save file it says that all save files are empty. I am using the Delta emulator and the .gba file from the latest release.

**Comment by Kippykip** [comment]
Emulators aren't picking up the correct save type. It's supposed to be SRAM

**Comment by ProvokedGamer** [comment]
Ah I see. Is there anything I can do on my end or is this an emulator issue/Delta emulator issue?

**Comment by doomhack** [comment]
Try the latest build. This should fix it.

**Comment by ProvokedGamer** [comment]
It works! The I'm able to save and they appear. 

Once you load a save, it takes you to the beginning of the level that save was saved at. Is that normal?

**Comment by doomhack** [comment]
Yes, that is normal. There isn't space to fully serialize out level state.

**Comment by ProvokedGamer** [comment]
Ok, everything's working then so I'll close this issue
